### PR TITLE
✨ Update Dropdown Menu Styling and Animations

### PR DESCRIPTION
**Pull request by MohamadSafi**
## 📖  description
This PR aims to enhance the dropdown menu styling ( Just thought that I wanna do it, So Why Not? ). 
The updates include:
- Improved color scheme with better contrast and a cohesive theme.
- Added hover and focus effects for a more interactive user experience.
- Implemented subtle animations for smoother transitions.
- Adjusted spacing and borders for a cleaner layout.

These changes aim to make the dropdown more engaging and fun while maintaining consistency with the website's overall design, below is a before & after demonstration:
## 📷 screenshot/video
<div style="display: flex; gap: 10px;">
    Before
    After
</div>

## 🐛  type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 🏁  checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (No need to!)
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by parzuko** [comment]
This looks good @MohamadSafi 
We will go ahead with the merge following a current PR of ours due merging. Thanks for contributing, check back here for updates ✨ ✌️

**Comment by MohamadSafi** [comment]
Hi @parzuko any new news about this PR?

**Comment by parzuko** [comment]
> Hi @parzuko any new news about this PR?

Can you pull and include the new `Spirit Karrot` endpoint in this as well?

**Comment by MohamadSafi** [comment]
> Can you take a pull from main and include the new `Spirit Karrot` endpoint in this as well?
Sure thing!

**Comment by MohamadSafi** [comment]
> > Hi @parzuko any new news about this PR?
> 
> Can you take a pull from main and include the new `Spirit Karrot` endpoint in this as well?

Done 👍

**Review by parzuko — APPROVED** [review]
LGTM 🚀

**Pull request merged**
